spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:fin_db}?allowMultiQueries=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Denisdzi88}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: none


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml


logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: debug
    root: info

server:
    port: 8080