spring:
  main:
    banner-mode: off

  datasource:
    url: ${DATASOURCE_URL}?allowMultiQueries=true
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: none

#  sql:
#    init:
#      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql
#      mode: always
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
    #   clear-checksums: true


logging:
  level:
    # org.springframework.jdbc.datasource.init.ScriptUtils: debug
    root: info




server:
    port: 8080


