spring:
  main:
    banner-mode: off

  datasource:
    url: ${DATASOURCE_URL}?allowMultiQueries=true
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: none


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml


logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: debug
    root: info

server:
    port: 8080